import './globals.css'
import localFont from 'next/font/local'

const MetropolisRegular = localFont({
  src: '../fonts/Metropolis-Regular.ttf',
})

export const metadata = {
  title: 'E learning',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={MetropolisRegular.className}>
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
